<?php


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
        'key' => 'group_5c599a27e446a',
        'title' => __('Event form', 'event-integration'),
        'fields' => array(
            0 => array(
                'key' => 'field_5c5acaf760b21',
                'label' => __('Settings', 'event-integration'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            1 => array(
                'key' => 'field_5c599a30583d3',
                'label' => __('User groups', 'event-integration'),
                'name' => 'user_groups',
                'type' => 'text',
                'instructions' => __('Comma separated list of user group IDs.', 'event-integration'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            2 => array(
                'key' => 'field_5c59a5630d99b',
                'label' => __('Form name', 'event-integration'),
                'name' => 'client_name',
                'type' => 'text',
                'instructions' => __('Name the form for easier grouping of events.', 'event-integration'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            3 => array(
                'key' => 'field_5c5acb1f60b22',
                'label' => __('Fields', 'event-integration'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            4 => array(
                'key' => 'field_5c5acd9eda6e4',
                'label' => __('Field settings', 'event-integration'),
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => __('Add custom field labels and descriptions. Leave empty to use default texts.
You can hide whole fields that are not required.', 'event-integration'),
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            5 => array(
                'key' => 'field_5c5acb3160b23',
                'label' => __('Title', 'event-integration'),
                'name' => 'title',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5acb7960b24',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5accbd60b25',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5acce460b26',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            6 => array(
                'key' => 'field_5c5ae353d04bf',
                'label' => __('Content', 'event-integration'),
                'name' => 'content',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5ae353d04c0',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5ae353d04c1',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'br',
                    ),
                    2 => array(
                        'key' => 'field_5c5ae353d04c2',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            7 => array(
                'key' => 'field_5c5aec63065fa',
                'label' => __('Occasion', 'event-integration'),
                'name' => 'occasion',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5aec63065fb',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5aec63065fc',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5aec63065fd',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            8 => array(
                'key' => 'field_5c5af02c4c2be',
                'label' => __('Event link', 'event-integration'),
                'name' => 'event_link',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5af02c4c2bf',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5af02c4c2c0',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5af03e4c2c2',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5af02c4c2c1',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c042bb0ce7',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            9 => array(
                'key' => 'field_5c5af554d6769',
                'label' => __('Link to booking', 'event-integration'),
                'name' => 'booking_link',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5af554d676a',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5af554d676b',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5af554d676d',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5af554d676c',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c073ca9f3b',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            10 => array(
                'key' => 'field_5c5afc69fcc25',
                'label' => __('Price adult', 'event-integration'),
                'name' => 'price_adult',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5afc69fcc26',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5afc69fcc27',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5afc69fcc29',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5afc69fcc28',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c0a99a9f3c',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            11 => array(
                'key' => 'field_5c5afc8e55866',
                'label' => __('Price student', 'event-integration'),
                'name' => 'price_student',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5afc8e55867',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5afc8e55868',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5afc8e5586a',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5afc8e55869',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c0b946b699',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            12 => array(
                'key' => 'field_5c5afe5d43c32',
                'label' => __('Price children', 'event-integration'),
                'name' => 'price_children',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5afe5d43c33',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5afe5d43c34',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5afe5d43c36',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5afe5d43c35',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c0c046b69a',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            13 => array(
                'key' => 'field_5c5b00e9a0100',
                'label' => __('Children age', 'event-integration'),
                'name' => 'children_age',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5b00e9a0101',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5b00e9a0102',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5b00e9a0104',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5b00e9a0103',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c0fe3bf539',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            14 => array(
                'key' => 'field_5c5b0163d0b88',
                'label' => __('Price senior', 'event-integration'),
                'name' => 'price_senior',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5b0163d0b89',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5b0163d0b8a',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5b0163d0b8c',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5b0163d0b8b',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c1fead2056',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            15 => array(
                'key' => 'field_5c5b03a60aeaa',
                'label' => __('Senior age', 'event-integration'),
                'name' => 'senior_age',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5b03a60aeab',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5b03a60aeac',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5b03a60aeae',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5b03a60aead',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c2066d2057',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            16 => array(
                'key' => 'field_5c5b03fa174d0',
                'label' => __('Age group', 'event-integration'),
                'name' => 'age_group',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5b03fa174d1',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5b03fa174d2',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5b03fa174d4',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5b03fa174d3',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c209abab7e',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            17 => array(
                'key' => 'field_5c5bdf7177d9a',
                'label' => __('Organizer', 'event-integration'),
                'name' => 'organizer',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5bdf7277d9b',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5bdf7277d9c',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5bdf7277d9e',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5bdf7277d9d',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            18 => array(
                'key' => 'field_5c5bdfceca4a3',
                'label' => __('Location', 'event-integration'),
                'name' => 'location',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5bdfceca4a4',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5bdfceca4a5',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5bdfceca4a7',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5bdfceca4a6',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            19 => array(
                'key' => 'field_5c5be0a53c130',
                'label' => __('Accessibility', 'event-integration'),
                'name' => 'accessibility',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5be0a53c131',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5be0a53c132',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5be0a53c134',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5be0a53c133',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            20 => array(
                'key' => 'field_5c5be779e22fa',
                'label' => __('Event categories', 'event-integration'),
                'name' => 'event_categories',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5be779e22fb',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5be779e22fc',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5be779e22fe',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5be779e22fd',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5be78fe22ff',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            21 => array(
                'key' => 'field_5e81e85247643',
                'label' => __('Tags', 'event-integration'),
                'name' => 'event_tags',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5e81e85247644',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5e81e85247645',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5e81e85247646',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5e81e85247647',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5e81e85247648',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            22 => array(
                'key' => 'field_5c5bef647b52f',
                'label' => __('Image', 'event-integration'),
                'name' => 'image_input',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5bef647b530',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5bef647b531',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5bef647b533',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5bef647b532',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5bef647b534',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            23 => array(
                'key' => 'field_5c5bff444a675',
                'label' => __('Email', 'event-integration'),
                'name' => 'submitter_email',
                'type' => 'group',
                'instructions' => __('Email address to the person who submitted the event.', 'event-integration'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5bff444a676',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5bff444a677',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5bff444a679',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5bff444a678',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5bff444a67a',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
            24 => array(
                'key' => 'field_5c5c005d26639',
                'label' => __('Phone number', 'event-integration'),
                'name' => 'submitter_phone',
                'type' => 'group',
                'instructions' => __('Phone numer to the person who submitted the event.', 'event-integration'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    0 => array(
                        'key' => 'field_5c5c005d2663a',
                        'label' => __('Label', 'event-integration'),
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    1 => array(
                        'key' => 'field_5c5c005d2663b',
                        'label' => __('Description', 'event-integration'),
                        'name' => 'description',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    2 => array(
                        'key' => 'field_5c5c005d2663d',
                        'label' => __('Hide field', 'event-integration'),
                        'name' => 'hidden',
                        'type' => 'true_false',
                        'instructions' => __('Hide the whole field.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    3 => array(
                        'key' => 'field_5c5c005d2663c',
                        'label' => __('Hide description', 'event-integration'),
                        'name' => 'hidden_description',
                        'type' => 'true_false',
                        'instructions' => __('Hide field description.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    4 => array(
                        'key' => 'field_5c5c005d2663e',
                        'label' => __('Required', 'event-integration'),
                        'name' => 'required',
                        'type' => 'true_false',
                        'instructions' => __('Select if the field is required.', 'event-integration'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            0 => array(
                0 => array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-event-submit',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
}
