<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_583557753bd73',
    'title' => __('Event Manager Integration', 'event-integration'),
    'fields' => array(
        0 => array(
            'key' => 'field_673c3cb443698',
            'label' => __('General settings', 'event-integration'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_588f3ef76094c',
            'label' => __('API url', 'event-integration'),
            'name' => 'event_api_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('Url to Event Manager API wp/v2 namespace. <br> E.g. https://host/wp-json/wp/v2', 'event-integration'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        2 => array(
            'key' => 'field_5835579f883ff',
            'label' => __('Days ahead', 'event-integration'),
            'name' => 'days_ahead',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => __('Import events that occurs within given number of days. Try to keep it as short as possible to avoid unnecessary datatransfer.', 'event-integration'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 30,
            'placeholder' => '',
            'prepend' => '',
            'append' => __('days', 'event-integration'),
            'min' => 1,
            'max' => 730,
            'step' => '',
        ),
        3 => array(
            'key' => 'field_5835581488400',
            'label' => __('Daily import', 'event-integration'),
            'name' => 'event_daily_import',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Enable daily automatic import from Event Manager API', 'event-integration'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        4 => array(
            'key' => 'field_587f86dc8f7b7',
            'label' => __('Post status', 'event-integration'),
            'name' => 'event_post_status',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => __('Select status of imported events.', 'event-integration'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'draft' => __('Draft', 'event-integration'),
                'publish' => __('Published', 'event-integration'),
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => __('publish', 'event-integration'),
            'layout' => 'vertical',
            'return_format' => 'value',
        ),
        5 => array(
            'key' => 'field_58feee2f256cd',
            'label' => __('Unpublish long lasting events', 'event-integration'),
            'name' => 'event_unpublish_limit',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => __('Automatically unpublish events lasting longer than given limit. Set to -1 to set no limit.', 'event-integration'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 5,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => -1,
            'max' => '',
            'step' => '',
        ),
        6 => array(
            'key' => 'field_58e380646fa6f',
            'label' => __('Visa knapp för att uppdatera importerade evenemang', 'event-integration'),
            'name' => 'event_update_button',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Visa uppdatera-knapp', 'event-integration'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        7 => array(
            'key' => 'field_58a56eaa0c2ad',
            'label' => __('OAuth1 end point root url', 'event-integration'),
            'name' => 'event_api_oauth_url',
            'aria-label' => '',
            'type' => 'url',
            'instructions' => __('Url can be found under section "authentication" in your API root.<br> E.g. https://host/oauth1<br> <br> Authorization is only needed when you want to post data to the API.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        8 => array(
            'key' => 'field_5b0e5b3be7bf7',
            'label' => __('Import filters', 'event-integration'),
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        9 => array(
            'key' => 'field_586bc598f2777',
            'label' => __('Import from selected user groups', 'event-integration'),
            'name' => 'event_filter_group',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => __('Select the user groups that you want to import events from. Leave empty to import from all groups.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'event_groups',
            'field_type' => 'checkbox',
            'allow_null' => 0,
            'add_term' => 0,
            'save_terms' => 1,
            'load_terms' => 0,
            'return_format' => 'object',
            'multiple' => 0,
            'bidirectional_target' => array(
            ),
        ),
        10 => array(
            'key' => 'field_5846ca031ffcb',
            'label' => __('Import from selected categories', 'event-integration'),
            'name' => 'event_filter_cat',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('Enter the name of the categories that you want to import events from. Separate with commas. Leave blank to import from all categories.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        11 => array(
            'key' => 'field_5846db8b3cf78',
            'label' => __('Import from selected tags', 'event-integration'),
            'name' => 'event_filter_tag',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => __('Enter the name of the tags that you want to import events from. Separate with commas. Leave blank to import from all tags.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        12 => array(
            'key' => 'field_5b1e890a063c4',
            'label' => __('Import internal events', 'event-integration'),
            'name' => 'event_internal_events',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Select if only internal (organization) events should be imported.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        13 => array(
            'key' => 'field_5b0e5a49c8fab',
            'label' => __('Import from geographic location', 'event-integration'),
            'name' => 'event_import_from_location',
            'aria-label' => '',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'no' => __('No', 'event-integration'),
                'point' => __('Single point', 'event-integration'),
                'area' => __('Drawn area', 'event-integration'),
            ),
            'allow_null' => 0,
            'default_value' => __('no', 'event-integration'),
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        14 => array(
            'key' => 'field_58aaeaa46781b',
            'label' => __('From a single point', 'event-integration'),
            'name' => 'event_import_geographic',
            'aria-label' => '',
            'type' => 'google_map',
            'instructions' => __('Import events that occurs at a specified location.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5b0e5a49c8fab',
                        'operator' => '==',
                        'value' => 'point',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => '56.046467',
            'center_lng' => '12.694512',
            'zoom' => 16,
            'height' => '',
        ),
        15 => array(
            'key' => 'field_58aaec066781c',
            'label' => __('Distance from location', 'event-integration'),
            'name' => 'event_geographic_distance',
            'aria-label' => '',
            'type' => 'number',
            'instructions' => __('To get events occurring nearby the given location, enter maximum distance in km. Leave blank to only get events from the exact position.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5b0e5a49c8fab',
                        'operator' => '==',
                        'value' => 'point',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        16 => array(
            'key' => 'field_5b0e6394d6399',
            'label' => __('Drawn area', 'event-integration'),
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5b0e5a49c8fab',
                        'operator' => '==',
                        'value' => 'area',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => 'draw-map-container',
            ),
            'message' => __('Import events that occurs inside the drawn area. Draw the area by clicking each point on the map. Maximum number of points is 8.', 'event-integration'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        17 => array(
            'key' => 'field_673c3cc743699',
            'label' => __('Details page', 'event-integration'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        18 => array(
            'key' => 'field_673c3cf64369a',
            'label' => __('Clean hero image', 'event-integration'),
            'name' => 'event_single_clean_hero',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Skip detailed information in hero image', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Yes', 'event-integration'),
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'event-options',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}