<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_58526d565e1f5',
    'title' => __('Shortcode settings', 'event-integration'),
    'fields' => array(
        0 => array(
            'key' => 'field_585278962daaf',
            'label' => __('Information', 'event-integration'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_585278b82dab0',
            'label' => __('Shortcodes', 'event-integration'),
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Shortcodes to display event information. Add the shortcode to your single event template file.<br><br>Display as accordion:<br>[single_event_accordion]<br><br>Display as table:<br>[single_event_information]', 'event-integration'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        2 => array(
            'key' => 'field_585279446b5da',
            'label' => __('Display fields', 'event-integration'),
            'name' => 'event_shortc_fields',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'information' => __('Information', 'event-integration'),
                'occasion' => __('Occasions', 'event-integration'),
                'location' => __('Location', 'event-integration'),
                'additional_locations' => __('Additional locations', 'event-integration'),
                'organizers' => __('Organizers', 'event-integration'),
                'sponsors' => __('Sponsors', 'event-integration'),
                'booking' => __('Booking information', 'event-integration'),
                'links' => __('Links', 'event-integration'),
                'contact' => __('Contact', 'event-integration'),
                'map' => __('Map', 'event-integration'),
            ),
            'allow_custom' => 0,
            'save_custom' => 0,
            'default_value' => array(
                0 => 'information',
                1 => 'occasion',
                2 => 'location',
                3 => 'additional_locations',
                4 => 'organizers',
                5 => 'sponsors',
                6 => 'booking',
                7 => 'links',
                8 => 'contact',
                9 => 'map',
            ),
            'layout' => 'vertical',
            'toggle' => 0,
            'return_format' => 'value',
        ),
        3 => array(
            'key' => 'field_5857b799e4d02',
            'label' => __('Wrapper div class', 'event-integration'),
            'name' => 'event_shortc_wrapper',
            'type' => 'text',
            'instructions' => __('Add custom classes to div that wraps around the info boxes on shortcode: [single_event_information]. Useful when creating responsive grids. Separate with comma.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        4 => array(
            'key' => 'field_5857b7f0e4d03',
            'label' => __('Inner div box class', 'event-integration'),
            'name' => 'event_shortc_inner',
            'type' => 'text',
            'instructions' => __('Add custom classes to inner div boxes that contains the event information on shortcode: [single_event_information]. Useful when creating responsive grids. Separate with comma.', 'event-integration'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        5 => array(
            'key' => 'field_585270b4dad2b',
            'label' => __('Gallery', 'event-integration'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        6 => array(
            'key' => 'field_5852713b299b6',
            'label' => __('Gallery shortcode', 'event-integration'),
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Gallery images is stored as attached images. You can use WordPress own shortcode [gallery] to display the images.', 'event-integration'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'event-options',
            ),
        ),
    ),
    'menu_order' => 1,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}