<?php

namespace EventManagerIntegration\Acf;

/**
 * Load local ACF field groups with PHP
 */

class AcfFields
{
    public function __construct()
    {
        add_action('acf/init', array($this, 'addLocalFieldGroups'));
    }

    public function addLocalFieldGroups()
    {
		if(function_exists('acf_add_local_field_group')) {

		// Event manager settings group
		acf_add_local_field_group(array (
		'key' => 'group_583557753bd73',
		'title' => __('Event Manager Integration', 'event-integration'),
		'fields' => array (
			array (
				'key' => 'field_588f3ef76094c',
				'label' => __('API url', 'event-integration'),
				'name' => 'event_api_url',
				'type' => 'url',
				'instructions' => __('Url to Event Manager API wp/v2 namespace. <br> E.g. https://host/wp-json/wp/v2', 'event-integration'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_5835579f883ff',
				'label' => __('Days ahead', 'event-integration'),
				'name' => 'days_ahead',
				'type' => 'number',
				'instructions' => __('Import events that occurs within given number of days.', 'event-integration'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 30,
				'placeholder' => '',
				'prepend' => '',
				'append' => __('days', 'event-integration'),
				'min' => 1,
				'max' => 365,
				'step' => '',
			),
			array (
				'key' => 'field_5835581488400',
				'label' => __('Daily import', 'event-integration'),
				'name' => 'event_daily_import',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => __('Enable daily automatic import from Event Manager API', 'event-integration'),
				'default_value' => 1,
			),
			array (
				'key' => 'field_587f86dc8f7b7',
				'label' => __('Post status', 'event-integration'),
				'name' => 'event_post_status',
				'type' => 'radio',
				'instructions' => __('Select status of imported events.', 'event-integration'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'draft' => __('Draft', 'event-integration'),
					'publish' => __('Published', 'event-integration'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'publish',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_586bc598f2777',
				'label' => __('Import from selected user groups', 'event-integration'),
				'name' => 'event_filter_group',
				'type' => 'taxonomy',
				'instructions' => __('Select the user groups that you want to import events from. Leave empty to import from all groups.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'event_groups',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'add_term' => 0,
				'save_terms' => 1,
				'load_terms' => 0,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5846ca031ffcb',
				'label' => __('Import from selected categories', 'event-integration'),
				'name' => 'event_filter_cat',
				'type' => 'text',
				'instructions' => __('Enter the name of the categories that you want to import events from. Separate with commas. Leave blank to import from all categories.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5846db8b3cf78',
				'label' => __('Import from selected tags', 'event-integration'),
				'name' => 'event_filter_tag',
				'type' => 'text',
				'instructions' => __('Enter the name of the tags that you want to import events from. Separate with commas. Leave blank to import from all tags.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5859206f23f1b',
				'label' => __('Single event image', 'event-integration'),
				'name' => 'event_single_image',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('Display attached event image below title header on single events.', 'event-integration'),
				'default_value' => 1,
			),
			array (
				'key' => 'field_58e380646fa6f',
				'label' => __('Show update button on edit event page', 'event-integration'),
				'name' => 'event_update_button',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('Show update button', 'event-integration'),
				'default_value' => 0,
			),
			array (
				'key' => 'field_58a56eaa0c2ad',
				'label' => __('OAuth1 end point root url', 'event-integration'),
				'name' => 'event_api_oauth_url',
				'type' => 'url',
				'instructions' => __('Url can be found under section "authentication" in your API root.<br> E.g. https://host/oauth1<br> <br> Authorization is only needed when you want to post data to the API.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_58aaf2615abcb',
				'label' => 'Google Maps JavaScript API key',
				'name' => 'google_geocode_key',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58aaeaa46781b',
				'label' => __('Import from location', 'event-integration'),
				'name' => 'event_import_geographic',
				'type' => 'google_map',
				'instructions' => __('Import events that occurs at a specified location.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'center_lat' => '56.046467',
				'center_lng' => '12.694512',
				'zoom' => 16,
				'height' => '',
			),
			array (
				'key' => 'field_58aaec066781c',
				'label' => __('Distance from location', 'event-integration'),
				'name' => 'event_geographic_distance',
				'type' => 'number',
				'instructions' => __('To get events occurring nearby the given location, enter maximum distance in km. Leave blank to only get events from the exact position.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		));

		// Shortcode settings
		acf_add_local_field_group(array (
			'key' => 'group_58526d565e1f5',
			'title' => __('Shortcode settings', 'event-integration'),
			'fields' => array (
				array (
					'key' => 'field_585278962daaf',
					'label' => __('Information', 'event-integration'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_585278b82dab0',
					'label' => __('Information shortcode', 'event-integration'),
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => __('Shortcode to display event information. Add the shortcode to your single event template file.<br> <br> [single_event_information]', 'event-integration'),
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array (
					'key' => 'field_585279446b5da',
					'label' => __('Display fields', 'event-integration'),
					'name' => 'event_shortc_fields',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'information' => __('Information', 'event-integration'),
						'occasion' => __('Occasions', 'event-integration'),
						'location' => __('Location', 'event-integration'),
						'additional_locations' => __('Additional locations', 'event-integration'),
						'organizers' => __('Organizers', 'event-integration'),
						'sponsors' => __('Sponsors', 'event-integration'),
						'booking' => __('Booking information', 'event-integration'),
						'links' => __('Links', 'event-integration'),
					),
					'default_value' => array (
						0 => 'information',
						1 => 'occasion',
						2 => 'location',
						3 => 'additional_locations',
						4 => 'organizers',
						5 => 'sponsors',
						6 => 'booking',
						7 => 'links',
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
				),
				array (
					'key' => 'field_5857b799e4d02',
					'label' => __('Wrapper div class', 'event-integration'),
					'name' => 'event_shortc_wrapper',
					'type' => 'text',
					'instructions' => __('Add custom classes to div that wraps around the info boxes. Useful when creating responsive grids. Separate with comma.', 'event-integration'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5857b7f0e4d03',
					'label' => __('Inner div box class', 'event-integration'),
					'name' => 'event_shortc_inner',
					'type' => 'text',
					'instructions' => __('Add custom classes to inner div boxes that contains the event information. Useful when creating responsive grids. Separate with comma.', 'event-integration'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_585270b4dad2b',
					'label' => __('Gallery', 'event-integration'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_5852713b299b6',
					'label' => __('Gallery shortcode', 'event-integration'),
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => __('Gallery images is stored as attached images. You can use WordPress own shortcode [gallery] to display the images.', 'event-integration'),
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options-options',
					),
				),
			),
			'menu_order' => 1,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
			'local' => 'json',
		));

		// Display events module settings
		acf_add_local_field_group(array (
		'key' => 'group_583fe4ee88439',
		'title' => __('Display events', 'event-integration'),
		'fields' => array (
			array (
				'key' => 'field_583fe58262287',
				'label' => __('Number of events to show', 'event-integration'),
				'name' => 'mod_event_limit',
				'type' => 'number',
				'instructions' => __('Set to -1 to show all.', 'event-integration'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => 5,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => -1,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_584ec8318df1d',
				'label' => __('Show pagination', 'event-integration'),
				'name' => 'mod_event_pagination',
				'type' => 'true_false',
				'instructions' => __('Display pagination buttons below the event list.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'message' => __('Show pagination', 'event-integration'),
				'default_value' => 1,
			),
			array (
				'key' => 'field_58e6370d4f34c',
				'label' => __('Archive link', 'event-integration'),
				'name' => 'mod_event_archive',
				'type' => 'true_false',
				'instructions' => __('Show link to event archive page.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'message' => __('Show link', 'event-integration'),
				'default_value' => 0,
			),
			array (
				'key' => 'field_583ffd8d10925',
				'label' => __('Days interval', 'event-integration'),
				'name' => 'mod_event_interval',
				'type' => 'number',
				'instructions' => __('Include events from today to the given number of days.', 'event-integration'),
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => 7,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_583fefb6634a1',
				'label' => __('Fields', 'event-integration'),
				'name' => 'mod_event_fields',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'occasion' => __('Occasion', 'event-integration'),
					'image' => __('Image', 'event-integration'),
					'location' => __('Location', 'event-integration'),
					'description' => __('Description', 'event-integration'),
				),
				'default_value' => array (
				),
				'layout' => 'vertical',
				'toggle' => 1,
				'return_format' => 'value',
			),
			array (
				'key' => 'field_58de5b2d62d45',
				'label' => __('Occasion position', 'event-integration'),
				'name' => 'mod_event_occ_pos',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_583fefb6634a1',
							'operator' => '==',
							'value' => 'occasion',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'below' => __('Below title', 'event-integration'),
					'left' => __('Left column', 'event-integration'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'below : Below title',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_583fee36634a0',
				'label' => __('Description letter limit', 'event-integration'),
				'name' => 'mod_event_descr_limit',
				'type' => 'number',
				'instructions' => __('Set to -1 to show the whole description.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_583fefb6634a1',
							'operator' => '==',
							'value' => 'description',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => -1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => -1,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_586cf5c8d3686',
				'label' => __('Groups', 'event-integration'),
				'name' => 'mod_event_groups_show',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('Show events from all groups', 'event-integration'),
				'default_value' => 1,
			),
			array (
				'key' => 'field_586cf5d0d3687',
				'label' => __('Select groups', 'event-integration'),
				'name' => 'mod_event_groups_list',
				'type' => 'taxonomy',
				'instructions' => __('Show events from the selected groups.', 'event-integration'),
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_586cf5c8d3686',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'event_groups',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_58455b0e93178',
				'label' => __('Categories', 'event-integration'),
				'name' => 'mod_event_categories_show',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('Show events from all categories', 'event-integration'),
				'default_value' => 1,
			),
			array (
				'key' => 'field_5845578c5f0a0',
				'label' => __('Select categories', 'event-integration'),
				'name' => 'mod_event_categories_list',
				'type' => 'taxonomy',
				'instructions' => __('Show events from the selected categories.', 'event-integration'),
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58455b0e93178',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'event_categories',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_58458b20dde03',
				'label' => __('Tags', 'event-integration'),
				'name' => 'mod_event_tags_show',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => __('Show events from all tags', 'event-integration'),
				'default_value' => 1,
			),
			array (
				'key' => 'field_58458b57dde04',
				'label' => __('Select tags', 'event-integration'),
				'name' => 'mod_event_tags_list',
				'type' => 'taxonomy',
				'instructions' => __('Show events from the selected tags.', 'event-integration'),
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58458b20dde03',
							'operator' => '!=',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'event_tags',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_584f9e68aa31a',
				'label' => __('Default image', 'event-integration'),
				'name' => 'mod_event_def_image',
				'type' => 'image',
				'instructions' => __('Will display if event image is missing.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'jpg, jpeg, png, gif',
			),
			array (
				'key' => 'field_58abf724d46f6',
				'label' => __('Location', 'event-integration'),
				'name' => 'mod_event_geographic',
				'type' => 'google_map',
				'instructions' => __('Show events that occurs at a specified location.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'center_lat' => '56.046467',
				'center_lng' => '12.694512',
				'zoom' => 16,
				'height' => '',
			),
			array (
				'key' => 'field_58abf72bd46f7',
				'label' => __('Distance from location', 'event-integration'),
				'name' => 'mod_event_distance',
				'type' => 'number',
				'instructions' => __('To show events occurring nearby the given location, enter maximum distance in km. Leave blank to only show events from the exact position.', 'event-integration'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'mod-event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		));

		}
    }
}
